### ISSUE TITLE
Checkbox colors

### ISSUE THREAD

**Issue by 0x92** [siimple/siimple#36]
I missed different color styles for the checkbox ui element so i added them in my css file.

.siimple-checkbox--navy input[type=checkbox]:checked + label {
    background-color: #57607c;;
}

.siimple-checkbox--green input[type=checkbox]:checked + label {
    background-color: #1add9f;;
}

.siimple-checkbox--teal input[type=checkbox]:checked + label {
    background-color: #18d2ba;;
}

.siimple-checkbox--blue input[type=checkbox]:checked + label {
    background-color: #4894f0;
}

.siimple-checkbox--purple input[type=checkbox]:checked + label {
    background-color: #b490f5;
}

.siimple-checkbox--pink input[type=checkbox]:checked + label {
    background-color: #f45b93;
}

.siimple-checkbox--red input[type=checkbox]:checked + label {
    background-color: #ff1a4f;
}

.siimple-checkbox--orange input[type=checkbox]:checked + label {
    background-color: #ff8463;
}

.siimple-checkbox--yellow input[type=checkbox]:checked + label {
    background-color: #ffbf00;
}

.siimple-checkbox--grey input[type=checkbox]:checked + label {
    background-color: #ebf2fa;
}

.siimple-checkbox--white input[type=checkbox]:checked + label {
    background-color: #fff;
}
![screenshot](https://user-images.githubusercontent.com/6593435/40715375-a50a75fa-6405-11e8-979d-0ced9bcce3ab.PNG)

same "issue" for the switch element

**Comment by jmjuanes** [comment]
Hi @0x92 
Colors modifiers are not available for switch, checkbox and radio elements (the last will be available in `v3.1.0`).

Do you really think it would be a good functionality to add in a future release?

**Comment by 0x92** [comment]
i think so. i would love it to build different color based UIs

And good work @jmjuanes i looked about 3hours about different css frameworks siimple was the best i found

**Comment by jmjuanes** [comment]
Ok, it will be added in `3.2.0`.

>And good work @jmjuanes i looked about 3hours about different css frameworks siimple was the best i found

Thank you so much!!! Please don't hesitate to contact me if you have any further questions.

**Comment by jmjuanes** [comment]
Hello @0x92 !

Sorry for the big delay. 

We were thinking about this functionality, and we have some problems because the dark color class will conflict with another class that we will add in a future to enable dark mode of checkbox, radio and switch (remember that the new colors introduced in `v3.1.0` are `primary`, `success`, `error`, `warning`, `light` and `dark`, and legacy colors will be deprecated a future major release).

I thought two alternative solutions: 
- We can create a variable in file `_variables.scss` to set the checkbox, radio and switch default checked colors. If you want to change the color, you can overwrite this variable and compile a new version of siimple with your own colors.
- We can add in the documentation a section with the custom style that you should add to your website in case you want to change the checkbox, radio and switch checked color.

What do you think?

**Comment by jmjuanes** [comment]
Hi @0x92 
Finally we added `siimple-{element}--error`, `siimple-{element}--success` and `siimple-{element}--warning` colors for **checkbox**, **switch** and **radio**.

Sorry for the delay.
