### ISSUE TITLE
Some changes for repository folder structure

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [siimple/siimple#37]
The repository folder structure needs some improvement. Those are just suggestion, so maybe you aren't agree with me.

- [ ] Delete `media` folder from the repository. Maybe can add into a website.
- [x] Remove `CODE_OF_CONDUCT` and `CONTRIBUTING.md` into `.github` folder because it makes noisy.
- [x] Change the name of license file to `LICENSE` because it is just text file not markdown.
- [x] Issue and Feature templates are missing.

If you want, I can work a PR for 2, 3 and 4.

Thank you.

**Comment by jmjuanes** [comment]
- Yes to 3 and 4. 
- I think that the `CODE_OF_CONDUCT` may be kept in the root of the repository. The `CONTRIBUTING.md` yes, should be moved into `.github` folder.
- No to the 1, because the logos in `media` are used in some places. For example, in the README and in the (new) documentation.

Thank you! :smile:
